### ISSUE TITLE
layer + bt profile switch

### ISSUE THREAD

**Issue by alextenev** [SebastianBehrens/zmk-config-ferris#1]
Hello,

I found your repo through this issue: https://github.com/zmkfirmware/zmk/issues/576

I'm trying to make a macro that switches layer and bt at the same time. same as your code below:

https://github.com/SebastianBehrens/zmk-config-ferris/blob/345ab96ab5424a6ea50b110b6fdab412b485f722/config/cradio.keymap#L228

did you get it to work? I copied your approach and it doesn't seem to work for me.

sorry for opening an issue, there seems no way to send you a dm.

cheers,
Alex

**Comment by SebastianBehrens** [comment]
Hi Alex,
Yes, this ultimately did work. Is your config compiling?
Can you manually switch the bt_channels to see whether the bluetooth slots are filled?
